### PR TITLE
Serve piwigo from folder of webserver

### PR DESCRIPTION
**Pull request by extorn**

### CODE REVIEW

**Comment by extorn** [comment]
The pertinent part of my nginx webserver configuration file that is needed with this pr is:

_N.b. I am hosting the gallery at http://myserver.com/piwigo_
```
location ~ (^/piwigo)(/\d+/.*) {
                set $piwigo_internal_image_uri $2;
                set $php_script_name '/piwigo/plugins/piwigo_privacy/get.php';
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index get.php;
                include /etc/nginx/fastcgi_params;
                # overwrite these params
                fastcgi_param SCRIPT_FILENAME $document_root$php_script_name;
                fastcgi_param SCRIPT_NAME $php_script_name;
                fastcgi_param REQUEST_URI $piwigo_internal_image_uri;
        }
```

**Comment by yonjah** [comment]
Do we still need this change or does https://github.com/yonjah/piwigo_privacy/pull/27 solve it as well ?
Also will this work if we are serving the file through the php code and not passing it back to nginx ?

**Comment by extorn** [comment]
This isn't needed.
I've just double checked and my working get.php on my server does not include this change.

**Comment by extorn** [comment]
Sorry for the confusion, I started off wanting to make then plugin work for me, and ended up making it work for others' circumstances too without realising that in the process I'd made my original fix obsolete.
To be honest, I also wasn't sure how much input you'd be happy with and I didn't have the desire to get into a back and forth make changes dialog, just to propose a solution and have that accelerate your understanding and crafting of something production worthy.

**Pull request closed without merging**
