### PR TITLE
fixed for cases where piwigo is located in a sub folder on your webserver

### PR DESCRIPTION
**Pull request by extorn**
The plugin did not work for me as my piwigo instance is set in a subfolder on my webserver
accessible as such Https://example.com/my_gallery
The changes here allow this plugin to continue to work in this instance.
I'm not a php developer, so if there is a better and or easier way, please let me know.

### CODE REVIEW

**Comment by yonjah** [comment]
@extorn  thank you for this pull request.

It seems weird that this locations are not relative to the install path.
Can you share your directory structures ?
I'll need to look into this a bit further.

If indeed we need to pass the relative path to the script as your fix suggest I would rather
we get the value by adding a config parameter.
It will be safer than getting it from the server input.

**Comment by extorn** [comment]
Hi.
My nginx site root is at /var/www
The piwigo code is all in a sub folder (piwigo)
The reason for making the website root /var/www is that I want to access the site at http://example.com/piwigo
The reason for this is that it sits behind a reverse proxy which doles out various subfolders to the appropriate servers. So, it is in fact this which passes through using proxy pass the http://example.com/piwigo to the nginx server running piwigo.
Originally, I had the piwigo website server hosted at / so, my proxy would still be passing through  http://example.com/piwigo but this would go to myinternalpiwigoserver/. However, the issue was that the piwigo server then thought it was hosted at  http://example.com/ rather than  http://example.com/piwigo so the combined css files were incorrectly referencing images at  http://example.com/images/xyz.gif or similar rather than http://example.com/piwigo/images/xyz.gif

Does that make sense? If not, I can perhaps upload snippets from nginx reverse proxy (you have my nginx piwigo server config in this PR) to clarify.

I initially used a config parameter, but then realised that it could be pulled off the front of the URI. I take your point though that this is not ideal in so much as a nefarious actor could theoretically use that to access somewhere deep in the website, though the extraction and use of the image id to sanity check the remaining part of the URI negates this I think.

**Comment by yonjah** [comment]
A Bit more info on the directory structure might be useful but I think I might be able to figure it out.
So if I understand correctly you are using the `piwigo_privacy_redirect_header` config and the redirect
doesn't include the `piwigo/`  path ?
If you unset the config to let the php script to serve the files does everything works as expected ?

I guess we can try deduce the path from the REQUEST_URI but I see that you had to remove the path from it. was it to get it to work with the plugin or did you need it to get piwigo to work at all ?

**Comment by extorn** [comment]
In answer to your question, I 'm not clear what you mean by "path" in your question.
Your code reads the request URI relative to the served piwigo root (in my case http://www.example.com/photos). So, I need to tell it the root is actually /photos and not as it thinks /.
Whether it is prefixed by the hostname etc or not is irrelevant to me, I just kept the code working as closely as possible to how it was originally. Are we talking at cross purposes here? I haven't removed the path to the externally accessible root of the app from the request uri. It just isn't present at all, hence the new parameter I added to provide it.

If I unset the `piwigo_privacy_redirect_header` parameter, then yes, it just works magically. In fact I did this on my old setup. I couldn't get it working without doing so. This time I had the confidence to investigate the plugin itself.

I hope the following extracts providing the full picture will allow you to see what is going on. My nginx understanding is limited to what I've learned sorting this out. Perhaps I missed something blindingly obvious to someone more experienced with it :-)

You can see from the code below that my proxy forwards all traffic looking for http://www.example.com/photos to the piwigo webserver.

This has been added to the end of my piwigo config file:

`
$conf['derivative_url_style']=1;
$conf['piwigo_privacy_redirect_header'] = 'X-Accel-Redirect';
// use this to work out what is going on in the plugin!
//$conf['piwigo_privacy_debug'] = true;
`

relevant section from my nginx proxy (which listens on www.example.com):

`
location ~ /photos {
        include /etc/nginx/proxy.conf;
        proxy_max_temp_file_size           0;
        proxy_set_header Host $http_host;
        proxy_set_header X_FORWARDED_PROTO https;
        proxy_pass https://internalNetworkPiwigoHostname:443;
}
`

proxy.conf has following content:

`
client_max_body_size 10m;
client_body_buffer_size 128k;
`
`
\#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
`
`
\# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;
`
`
\# Basic Proxy Config
proxy_set_header Host $host:$server_port;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
\#proxy_cookie_path / "/; HTTPOnly; Secure"; # enable at your own risk, may break certain apps
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 32 4k;
`
`
proxy_headers_hash_bucket_size 128;
`

**Comment by yonjah** [comment]
> In answer to your question, I 'm not clear what you mean by "path" in your question.
Sorry by path I meant the URL path piwigo is served under so if you access piwigo by
`http://www.example.com/photos/` the path will be `photos/`
> I haven't removed the path to the externally accessible root of the app from the request ur

In the nginx config you added -
```config
location ~ (^/piwigo)(/\d+/.*) {
        set $piwigo_app_root $1;
        set $piwigo_internal_image_uri $2;
        ...
        ...
        fastcgi_param  REQUEST_URI $piwigo_internal_image_uri;
        # pass the piwigo app root so it can be appended to the resulting uri
        fastcgi_param  APP_ROOT $piwigo_app_root;
    }
```
This will take a request to `https://example.com/piwigo/223/_data/i/upload/2018/11/19/20181119124531-551bdef06-sm.jpg` and will split the URL to
$1 = `/piwigo`
$2 = `/223/_data/i/upload/2018/11/19/20181119124531-551bdef06-sm.jpg`
and then
APP_ROOT = $1 = `/piwigo`
REQUEST_URI  = $2 = `/223/_data/i/upload/2018/11/19/20181119124531-551bdef06-sm.jpg`

this is different from a normal setup where  APP_ROOT is not available and REQUEST_URI contains the full URI `/piwigo/223/_data/i/upload/2018/11/19/20181119124531-551bdef06-sm.jpg`

I wonder if this is a change you had to do to get piwigo to work even without the plugin or was it done specifically to get it to work with piwigo_privacy
> 
> If I unset the `piwigo_privacy_redirect_header` parameter, then yes, it just works magically. In fact I did this on my old setup. I couldn't get it working without doing so. This time I had the confidence to investigate the plugin itself.

Thanks that explains the issue since the plugin will ask nginx to load `_data/i/upload/2018/11/19/20181119124531-551bdef06-sm.jpg` instead  `photos/_data/i/upload/2018/11/19/20181119124531-551bdef06-sm.jpg`.

**Comment by extorn** [comment]
The reason for breaking the /piwigo prefix off the uri path is that if you don't the plugin will fail because the first part of the path (/piwigo) is not a numeric (photo id).

**Comment by extorn** [comment]
This is a really unneccesary convoluted way to achieve this goal. I'll submit a much neater one.
Please update the plugin to say it supports piwigo 11 then :-) It appears to work fine.

**Pull request closed without merging**
